import { describe, it, expect } from "vitest";
import { sanitizeHtml } from "../lib/security/sanitize";

describe("HTML Sanitization Security Suite (DOMPurify)", () => {
  it("strips active <script> tags completely", () => {
    const dirty = '<p>Normal text</p><script>alert("XSS")</script>';
    const clean = sanitizeHtml(dirty);
    expect(clean).not.toContain("<script>");
    expect(clean).not.toContain("alert");
    expect(clean).toContain("<p>Normal text</p>");
  });

  it("neutralizes <img src=x onerror=...> handlers while preserving benign attributes", () => {
    const dirty = '<img src="https://example.com/pic.jpg" alt="Photo" onerror="alert(document.cookie)" />';
    const clean = sanitizeHtml(dirty);
    expect(clean).not.toContain("onerror");
    expect(clean).not.toContain("alert");
    expect(clean).toContain('src="https://example.com/pic.jpg"');
    expect(clean).toContain('alt="Photo"');
  });

  it("strips inline event listeners like onclick, onmouseover, onload", () => {
    const dirty = `
      <div onmouseover="maliciousCode()" onclick="stealData()">
        <p onload="evil()">Click me</p>
      </div>
    `;
    const clean = sanitizeHtml(dirty);
    expect(clean).not.toContain("onmouseover");
    expect(clean).not.toContain("onclick");
    expect(clean).not.toContain("onload");
    expect(clean).toContain("Click me");
  });

  it("neutralizes dangerous URI schemes in anchor links (javascript:, data:)", () => {
    const dirty = '<a href="javascript:alert(1)">Malicious Link</a><a href="https://google.com">Safe Link</a>';
    const clean = sanitizeHtml(dirty);
    expect(clean).not.toContain("javascript:");
    expect(clean).toContain('href="https://google.com"');
    expect(clean).toContain("Safe Link");
  });

  it("forbids dangerous embedding tags (iframe, object, embed, form, input)", () => {
    const dirty = `
      <iframe src="https://evil.com"></iframe>
      <object data="malware.swf"></object>
      <embed src="exploit.pdf" />
      <form action="/steal"><input name="token" value="secret" /></form>
      <p>Legitimate paragraph</p>
    `;
    const clean = sanitizeHtml(dirty);
    expect(clean).not.toContain("<iframe");
    expect(clean).not.toContain("<object");
    expect(clean).not.toContain("<embed");
    expect(clean).not.toContain("<form");
    expect(clean).not.toContain("<input");
    expect(clean).toContain("<p>Legitimate paragraph</p>");
  });

  it("preserves legitimate rich-text formatting tags generated by Tiptap editor", () => {
    const legitimate = `
      <h1>Document Heading</h1>
      <h2>Subheading</h2>
      <p>This is <strong>bold</strong> and <em>italic</em> text with <u>underlines</u>.</p>
      <ul>
        <li>Bullet 1</li>
        <li>Bullet 2</li>
      </ul>
      <ol>
        <li>Ordered 1</li>
      </ol>
      <blockquote>A wise quote</blockquote>
      <pre><code>const x = 10;</code></pre>
    `;
    const clean = sanitizeHtml(legitimate);
    expect(clean).toContain("<h1>Document Heading</h1>");
    expect(clean).toContain("<h2>Subheading</h2>");
    expect(clean).toContain("<strong>bold</strong>");
    expect(clean).toContain("<em>italic</em>");
    expect(clean).toContain("<ul>");
    expect(clean).toContain("<li>Bullet 1</li>");
    expect(clean).toContain("<blockquote>A wise quote</blockquote>");
    expect(clean).toContain("<code>const x = 10;</code>");
  });

  it("gracefully handles null, undefined, or empty strings", () => {
    expect(sanitizeHtml(null)).toBe("");
    expect(sanitizeHtml(undefined)).toBe("");
    expect(sanitizeHtml("")).toBe("");
  });
});
